import { db } from '@/db';
import { flights } from '@/db/schema';

async function main() {
    const sampleFlights = [
        {
            flightNumber: 'DL101',
            airline: 'Delta Airlines',
            origin: 'JFK',
            destination: 'LHR',
            departureTime: '2024-12-20T08:00:00.000Z',
            arrivalTime: '2024-12-20T20:00:00.000Z',
            price: 650,
            totalSeats: 250,
            availableSeats: 200,
            status: 'scheduled',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            flightNumber: 'JL202',
            airline: 'Japan Airlines',
            origin: 'LAX',
            destination: 'NRT',
            departureTime: '2024-12-21T10:30:00.000Z',
            arrivalTime: '2024-12-22T14:30:00.000Z',
            price: 850,
            totalSeats: 300,
            availableSeats: 250,
            status: 'scheduled',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            flightNumber: 'AF303',
            airline: 'Air France',
            origin: 'SFO',
            destination: 'CDG',
            departureTime: '2024-12-22T14:00:00.000Z',
            arrivalTime: '2024-12-23T09:00:00.000Z',
            price: 720,
            totalSeats: 200,
            availableSeats: 150,
            status: 'scheduled',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            flightNumber: 'EK404',
            airline: 'Emirates',
            origin: 'ORD',
            destination: 'DXB',
            departureTime: '2024-12-23T22:00:00.000Z',
            arrivalTime: '2024-12-24T18:00:00.000Z',
            price: 920,
            totalSeats: 280,
            availableSeats: 220,
            status: 'scheduled',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            flightNumber: 'IB505',
            airline: 'Iberia',
            origin: 'MIA',
            destination: 'BCN',
            departureTime: '2024-12-24T11:00:00.000Z',
            arrivalTime: '2024-12-24T23:00:00.000Z',
            price: 580,
            totalSeats: 180,
            availableSeats: 120,
            status: 'scheduled',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            flightNumber: 'SQ606',
            airline: 'Singapore Airlines',
            origin: 'SEA',
            destination: 'SIN',
            departureTime: '2024-12-25T16:00:00.000Z',
            arrivalTime: '2024-12-26T22:00:00.000Z',
            price: 980,
            totalSeats: 300,
            availableSeats: 280,
            status: 'scheduled',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            flightNumber: 'KL707',
            airline: 'KLM',
            origin: 'BOS',
            destination: 'AMS',
            departureTime: '2024-12-26T19:00:00.000Z',
            arrivalTime: '2024-12-27T08:00:00.000Z',
            price: 670,
            totalSeats: 220,
            availableSeats: 180,
            status: 'scheduled',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            flightNumber: 'LH808',
            airline: 'Lufthansa',
            origin: 'DEN',
            destination: 'FRA',
            departureTime: '2024-12-27T13:00:00.000Z',
            arrivalTime: '2024-12-28T06:00:00.000Z',
            price: 710,
            totalSeats: 240,
            availableSeats: 200,
            status: 'scheduled',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(flights).values(sampleFlights);
    
    console.log('✅ Flights seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});